-- MySQL Script generated by MySQL Workbench
-- Tue Jun 26 11:16:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema homenventorydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `homenventorydb` ;

-- -----------------------------------------------------
-- Schema homenventorydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `homenventorydb` DEFAULT CHARACTER SET latin1 ;
USE `homenventorydb` ;

-- -----------------------------------------------------
-- Table `homenventorydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homenventorydb`.`users` (
  `Email` VARCHAR(40) NOT NULL,
  `Password` VARCHAR(32) NOT NULL,
  `Phone` CHAR(10) NOT NULL UNIQUE,
  `FirstName` VARCHAR(50) NOT NULL,
  `LastName` VARCHAR(50) NOT NULL,
  `Active` BIT NOT NULL,
  `IsAdmin` BIT NOT NULL,
  PRIMARY KEY (`Email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homenventorydb`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homenventorydb`.`categories` (
  `CategoryID` INT NOT NULL AUTO_INCREMENT,
  `CategoryName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CategoryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homenventorydb`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homenventorydb`.`items` (
  `ItemID` INT NOT NULL AUTO_INCREMENT,
  `Category` INT NOT NULL,
  `ItemName` VARCHAR(45) NOT NULL,
  `Price` DOUBLE NOT NULL,
  `Owner` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`ItemID`),
  INDEX `fk_items_Categories_idx` (`Category` ASC),
  INDEX `fk_items_users1_idx` (`Owner` ASC),
  CONSTRAINT `fk_items_Categories`
    FOREIGN KEY (`Category`)
    REFERENCES `homenventorydb`.`categories` (`CategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_items_users1`
    FOREIGN KEY (`Owner`)
    REFERENCES `homenventorydb`.`users` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `categories` (`CategoryName`) VALUES ('kitchen');
INSERT INTO `categories` (`CategoryName`) VALUES ('bathroom');
INSERT INTO `categories` (`CategoryName`) VALUES ('living room');
INSERT INTO `categories` (`CategoryName`) VALUES ('basement');
INSERT INTO `categories` (`CategoryName`) VALUES ('bedrooom');
INSERT INTO `categories` (`CategoryName`) VALUES ('garage');
INSERT INTO `categories` (`CategoryName`) VALUES ('office');
INSERT INTO `categories` (`CategoryName`) VALUES ('utility room');
INSERT INTO `categories` (`CategoryName`) VALUES ('storage');
INSERT INTO `categories` (`CategoryName`) VALUES ('other');

INSERT INTO `users` (`Email`,`Password`,`Phone`,`FirstName`,`LastName`,`Active`,`IsAdmin`) VALUES ('admin@asd.as','password','1234567890','Admin','Admin',1,1);
INSERT INTO `users` (`Email`,`Password`,`Phone`,`FirstName`,`LastName`,`Active`,`IsAdmin`) VALUES ('admin2@asd.as','password','1112223333','Admin2','Admin2',0,1);
INSERT INTO `users` (`Email`,`Password`,`Phone`,`FirstName`,`LastName`,`Active`,`IsAdmin`) VALUES ('anne@asd.as','password','8005551829','Anne','Annerson',1,0);
INSERT INTO `users` (`Email`,`Password`,`Phone`,`FirstName`,`LastName`,`Active`,`IsAdmin`) VALUES ('barb@asd.as','password','6873542222','Barb','Barber',0,0);
INSERT INTO `users` (`Email`,`Password`,`Phone`,`FirstName`,`LastName`,`Active`,`IsAdmin`) VALUES ('don@asd.as','password','8005551829','don','Donerson',1,0);
INSERT INTO `users` (`Email`,`Password`,`Phone`,`FirstName`,`LastName`,`Active`,`IsAdmin`) VALUES ('carl@asd.as','password','6873542222','Carl','Carler',0,0);

INSERT INTO `items` (`Category`,`ItemName`,`Price`,`Owner`) VALUES (1,'blender',29.99,'anne@asd.as');
INSERT INTO `items` (`Category`,`ItemName`,`Price`,`Owner`) VALUES (1,'toaster',19.99,'anne@asd.as');
INSERT INTO `items` (`Category`,`ItemName`,`Price`,`Owner`) VALUES (3,'lamp',5,'anne@asd.as');
INSERT INTO `items` (`Category`,`ItemName`,`Price`,`Owner`) VALUES (6,'winter tires',200,'anne@asd.as');
INSERT INTO `items` (`Category`,`ItemName`,`Price`,`Owner`) VALUES (5,'dresser',50,'anne@asd.as');